# Site settings
title: Walt You - 知行合一
name: Walt You - 知行合一
url: "http://waltyou.github.io"
email: waltyou@163.com
description: Walt You - 知行合一
baseurl: "" # the subpath of your site, e.g. /blog/
github_username: waltyou # Github ID
baidutongji_id: d601aa59a7cce69b0847dcc1deb3eb53 # 百度统计 ID
google-analytics_id: UA-116533568-1 # google analytics id
logo_image: "/images/logo.png"  # LOGO 图片地址
# Build settings
gems: [jekyll-paginate]
highlighter: rouge
permalink: /:title/
paginate: 8
paginate_path: page/:num
# 目录深度
kramdown:
  toc_levels: 1..2
# seo
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
 